alias k="kubectl"
alias kc="kubectx"
alias kn="kubens"
alias h="helm"
alias tf="terraform"
alias a="ansible"
alias ap="ansible-playbook"
alias l="ls -F"
alias la="ls -aF"
alias ls="eza --group-directories-first"
alias ll="eza --group-directories-first -l"
alias tree="eza -T"
alias rm="rm -i"
alias bat="/usr/bin/batcat"

